language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test --verbose
  - cargo test --verbose -- --ignored
  - cargo test --verbose --features visual-debug -- --ignored
before_install:
  - sudo apt-get install -y libxml2-utils
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    update: true
