[package]
name = "railroad"
version = "0.3.2"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
description = "A library to create syntax-diagrams as Scalable Vector Graphics"
repository = "https://github.com/lukaslueg/railroad"
documentation = "https://docs.rs/railroad"
readme = "README.md"
exclude = ["examples/*.jpeg", "examples/*.png", "examples/*.html"]
edition = "2021"

[features]
default = [ "resvg" ]
visual-debug = []

[dependencies]
unicode-width = "0.1"
resvg = { version = "0.42", optional=true, features=["text", "system-fonts", "memmap-fonts"] }

[dev-dependencies]
railroad_verification = "0.1"

[[example]]
name = "render"
required-features = [ "resvg" ]

[package.metadata.docs.rs]
features = [ "resvg" ]
